name: privacylens_probing
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.16
  - pip=25.0
  - python=3.11.11
  - readline=8.2
  - setuptools=75.8.0
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - absl-py==2.2.2
      - accelerate==1.6.0
      - adal==1.2.7
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.16
      - aiosignal==1.3.2
      - altair==5.5.0
      - annotated-types==0.7.0
      - anyio==3.7.1
      - argcomplete==3.6.2
      - asgiref==3.8.1
      - attrs==25.3.0
      - azure-common==1.1.28
      - azure-core==1.33.0
      - azure-graphrbac==0.61.2
      - azure-identity==1.21.0
      - azure-mgmt-authorization==4.0.0
      - azure-mgmt-containerregistry==10.3.0
      - azure-mgmt-core==1.5.0
      - azure-mgmt-keyvault==10.3.1
      - azure-mgmt-network==28.1.0
      - azure-mgmt-resource==23.3.0
      - azure-mgmt-storage==22.1.1
      - azureml-core==1.60.0
      - azureml-mlflow
      - backoff==2.2.1
      - backports-tempfile==1.0
      - backports-weakref==1.0.post1
      - bcrypt==4.3.0
      - beautifulsoup4==4.13.3
      - bitsandbytes==0.45.5
      - black==25.1.0
      - blinker==1.9.0
      - build==1.2.2.post1
      - cachetools==5.5.2
      - certifi==2025.1.31
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - chroma-hnswlib==0.7.6
      - chromadb==1.0.4
      - click==8.1.8
      - cloudpickle==3.1.1
      - cmake==4.0.0
      - coloredlogs==15.0.1
      - contextlib2==21.6.0
      - contourpy==1.3.1
      - cryptography==44.0.2
      - cycler==0.12.1
      - dataclasses-json==0.5.14
      - deprecated==1.2.18
      - diskcache==5.6.3
      - distro==1.9.0
      - docker==7.1.0
      - durationpy==0.9
      - fastapi==0.115.9
      - filelock==3.18.0
      - fire==0.7.0
      - flatbuffers==25.2.10
      - fonttools==4.57.0
      - frozenlist==1.5.0
      - fsspec==2025.3.2
      - git+https://github.com/dhh1995/PromptCoder.git#egg=procoder
      - gitdb==4.0.12
      - gitpython==3.1.44
      - google-auth==2.38.0
      - googleapis-common-protos==1.69.2
      - greenlet==3.1.1
      - grpcio==1.71.0
      - h11==0.14.0
      - httpcore==1.0.8
      - httptools==0.6.4
      - httpx==0.28.1
      - huggingface-hub==0.30.2
      - humanfriendly==10.0
      - idna==3.10
      - importlib-metadata==8.6.1
      - importlib-resources==6.5.2
      - interegular==0.3.3
      - isodate==0.7.2
      - jeepney==0.9.0
      - jinja2==3.1.6
      - jiter==0.9.0
      - jmespath==1.0.1
      - joblib==1.4.2
      - jsonpickle==4.0.5
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - kiwisolver==1.4.8
      - knack==0.12.0
      - kubernetes==32.0.1
      - langchain==0.0.277
      - langsmith==0.0.92
      - lark==1.2.2
      - llvmlite==0.44.0
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - marshmallow==3.26.1
      - matplotlib==3.10.1
      - mdurl==0.1.2
      - mlflow
      - mmh3==5.1.0
      - monotonic==1.6
      - mpmath==1.3.0
      - msal==1.32.0
      - msal-extensions==1.3.1
      - msgpack==1.1.0
      - msrest==0.7.1
      - msrestazure==0.6.4.post1
      - multidict==6.4.3
      - mypy-extensions==1.0.0
      - narwhals==1.34.1
      - ndg-httpsclient==0.5.1
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - ninja==1.11.1.4
      - nltk==3.9.1
      - numba==0.61.2
      - numexpr==2.10.2
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - onnxruntime==1.21.0
      - openai==1.74.0
      - opentelemetry-api==1.32.0
      - opentelemetry-exporter-otlp-proto-common==1.32.0
      - opentelemetry-exporter-otlp-proto-grpc==1.32.0
      - opentelemetry-instrumentation==0.53b0
      - opentelemetry-instrumentation-asgi==0.53b0
      - opentelemetry-instrumentation-fastapi==0.53b0
      - opentelemetry-proto==1.32.0
      - opentelemetry-sdk==1.32.0
      - opentelemetry-semantic-conventions==0.53b0
      - opentelemetry-util-http==0.53b0
      - orjson==3.10.16
      - outlines==0.0.34
      - overrides==7.7.0
      - packaging==24.2
      - pandas==2.2.3
      - paramiko==3.5.1
      - pathspec==0.12.1
      - patsy==1.0.1
      - pillow==11.1.0
      - pkginfo==1.12.1.2
      - platformdirs==4.3.7
      - posthog==3.24.1
      - prometheus-client==0.21.1
      - propcache==0.3.1
      - protobuf==5.29.4
      - psutil==7.0.0
      - py-cpuinfo==9.0.0
      - pyarrow==19.0.1
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==2.22
      - pydantic==2.11.3
      - pydantic-core==2.33.1
      - pydeck==0.9.1
      - pygments==2.19.1
      - pyjwt==2.10.1
      - pynacl==1.5.0
      - pynvml==11.5.0
      - pyopenssl==25.0.0
      - pyparsing==3.2.3
      - pypika==0.48.9
      - pyproject-hooks==1.2.0
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.0
      - pytz==2025.2
      - pyyaml==6.0.2
      - ray==2.44.1
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - rich==14.0.0
      - roman==5.0
      - rouge-score==0.1.2
      - rpds-py==0.24.0
      - rsa==4.9
      - safetensors==0.5.3
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - seaborn==0.13.2
      - secretstorage==3.3.3
      - sentencepiece==0.2.0
      - shellingham==1.5.4
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.6
      - sqlalchemy==2.0.40
      - starlette==0.45.3
      - statsmodels==0.14.4
      - streamlit==1.44.1
      - sympy==1.13.1
      - tabulate==0.9.0
      - tenacity==8.5.0
      - termcolor==3.0.1
      - threadpoolctl==3.6.0
      - tiktoken==0.6.0
      - tokenizers==0.21.1
      - toml==0.10.2
      - torch==2.1.2
      - tornado==6.4.2
      - tqdm==4.67.1
      - tqdm_loggable
      - transformers==4.51.2
      - triton==2.1.0
      - typer==0.15.2
      - typing-extensions==4.13.2
      - typing-inspect==0.9.0
      - typing-inspection==0.4.0
      - tzdata==2025.2
      - urllib3==2.4.0
      - uvicorn==0.34.0
      - uvloop==0.21.0
      - vllm==0.4.0.post1
      - watchdog==6.0.0
      - watchfiles==1.0.5
      - websocket-client==1.8.0
      - websockets==15.0.1
      - wikipedia==1.4.0
      - wrapt==1.17.2
      - xformers==0.0.23.post1
      - yarl==1.19.0
      - zipp==3.21.0
